# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 11:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50, null=True)),
                ('slug', models.SlugField(null=True)),
                ('role', models.CharField(max_length=50, null=True)),
                ('bio', models.TextField(null=True)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('phone', models.CharField(max_length=50, null=True)),
                ('active', models.BooleanField(default=True)),
                ('photo', models.ImageField(blank=True, upload_to='team')),
                ('order_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Member',
                'verbose_name_plural': 'Members',
                'ordering': ('order_id',),
            },
        ),
        migrations.CreateModel(
            name='MemberSocial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.CharField(choices=[('LINKEDIN', 'LinkedIn'), ('TWITTER', 'Twitter'), ('FACEBOOK', 'Facebook'), ('INSTAGRAM', 'Instagram'), ('BEHANCE', 'Behance')], max_length=50)),
                ('url', models.URLField(max_length=250)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.Member')),
            ],
        ),
    ]
