# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 10:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_auto_20170902_1700'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membersocial',
            options={'ordering': ('order_id',), 'verbose_name': 'Social network', 'verbose_name_plural': 'Social networks'},
        ),
        migrations.AddField(
            model_name='membersocial',
            name='order_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
