# Generated by Django 2.0.1 on 2018-01-25 18:27

from django.db import migrations, models
import uuid


def create_uuid(apps, schema_editor):
    Member = apps.get_model('team', 'Member')
    for m in Member.objects.all():
        m.uuid = uuid.uuid4()
        m.save()


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0006_auto_20180125_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.RunPython(create_uuid),
        migrations.AlterField(
            model_name='device',
            name='uuid',
            field=models.UUIDField(unique=True)
        )
    ]
